### ISSUE TITLE
Problems with Event() loops in Python 3.10

### ISSUE THREAD

**Issue by schorschebob** [Snawoot/ssh-tarpit#11]
Trying to run ssh-tarpit with Python v3.10+ results in the following error message:
`TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary`

According to the [Python docs](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop):

> Deprecated since version 3.10: Deprecation warning is emitted if there is no running event loop. In future Python releases, this function will be an alias of [get_running_loop()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop).

Environment:
```
python3 --version
Python 3.10.4
```

Complete error message with stack trace:
```ssh-tarpit
Traceback (most recent call last):
  File "[...]python3/bin/ssh-tarpit", line 8, in <module>
    sys.exit(main())
  File "/opt/python3/lib/python3.10/site-packages/ssh_tarpit/__main__.py", line 178, in main
    loop.run_until_complete(amain(args, loop))
  File "/opt/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/python3/lib/python3.10/site-packages/ssh_tarpit/__main__.py", line 146, in amain
    exit_event = asyncio.Event(loop=loop)
  File "/opt/python3/lib/python3.10/asyncio/locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "/opt/python3/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary```

**Comment by Snawoot** [comment]
Thanks! Uploaded v0.4.2.
